var vm=new Vue({
	el:"#app",
	data:{
		author:"CanCan",
		shopList:[],
	},
	watch:{
		shopList:{
			handler:function(){

			},
			deep:true
		}
	},
	filters:{
		changePrice:function(value){
			return "￥"+value.toFixed(2);
		}
	},
	mounted:function(){
		this.$nextTick(function(){
			this.getJson();
		})
	},
	methods:{
		getJson:function(){
			this.$http.get("data/cartData.json").then(function(res){
				console.log("成功");
			},function(res){
				this.shopList=res.data.result.list;
			});
		},
		changeNumber:function(item,flag){
			if(flag>0){
				item.productQuantity++;
			}
			else{
				item.productQuantity--;	
				if(item.productQuantity<1)
					item.productQuantity=1;
			}
		}
	}
});