var vm=new Vue({
	el:"#app",
	data:{
		author:"CanCan",
		shopList:[],
		checkAll:false,
		total:0
	},
	watch:{
		shopList:{
			handler:function(){
				if(this.shopList[0].checked&&this.shopList[1].checked&&this.shopList[2].checked)
					this.checkAll=true;
				else
					this.checkAll=false;
				this.total=0;
				this.shopList.forEach(function(ele){					
					if(ele.checked)
						this.vm.total+=ele.productPrice*ele.productQuantity;
				});
			},
			deep:true
		}
	},
	filters:{
		changePrice:function(value){
			return "￥"+value.toFixed(2);
		}
	},
	mounted:function(){
		this.$nextTick(function(){
			this.getJson();
		})
	},
	methods:{
		getJson:function(){
			this.$http.get("data/cartData.json").then(function(res){
				console.log("成功");
			},function(res){
				this.shopList=res.data.result.list;
			});
		},
		changeNumber:function(item,flag){
			if(flag>0){
				item.productQuantity++;
			}
			else{
				item.productQuantity--;	
				if(item.productQuantity<1)
					item.productQuantity=1;
			}
		},
		select:function(item){
			if (!item.checked) {
				this.$set(item,"checked",true);
			}
			else
				item.checked=!item.checked;
		},
		selectAll:function(flag){
			var _this=this;
			if(flag){
				this.checkAll=true;
				this.shopList.forEach(function(ele){
					if (!ele.checked) {
						_this.$set(ele,"checked",true);
					}
					else
						ele.checked=true;
				});
			}
			else{
				this.checkAll=false;
				this.shopList.forEach(function(ele){
					if(!ele.checked){
						_this.$set(ele,"checked",false);
					}
					else
						ele.checked=false;
				});
			}
		}
	}
});